Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 17, in <module>
    import setuptools.version
  File "/usr/lib/python3/dist-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3289, in _initialize_master_working_set
    list(map(working_set.add_entry, sys.path))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 624, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2066, in find_on_path
    for dist in factory(fullpath):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2135, in distributions_from_metadata
    yield Distribution.from_location(
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2592, in from_location
    return cls(
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2996, in _reload_version
    md_version = self._get_version()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2774, in _get_version
    version = _version_from_file(lines)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2558, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2769, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1433, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1421, in get_metadata
    value = self._get(path)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1617, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/d/UserProjects/Joey/Unity/Simple-Ros-Communication/ROS_DEV_WS/install/simpleMSG/lib/python3.8/site-packages/simpleMSG-0.0.0-py3.8.egg-info/PKG-INFO'
